import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { products } from './schema';
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('dotenv').config({ path: '.env.local' });

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const DUMMY = {
  widthMm: 0, heightMm: 0,
  widthIn: 'N/A', heightIn: 'N/A',
  unitsPerRoll: 1,
  material: 'N/A', printType: 'N/A', labelColor: 'N/A',
  adhesiveType: 'N/A', rollCoreMm: 'N/A',
};

async function seed() {
  console.log('🌱 Seeding STA-BIL products...');

  // Clear existing products
  await db.delete(products);

  await db.insert(products).values([
    // ── GASOLINA ─────────────────────────────────────────────────────────
    {
      ...DUMMY,
      slug: 'stabil-fuel-stabilizer-storage',
      name: 'STA-BIL Fuel Stabilizer Storage',
      model: '22214',
      labelType: 'Gasolina',
      mainUse: 'Mantiene el combustible fresco hasta 24 meses. El #1 de EE.UU.',
      priceBob: '254.34',
      priceUsd: null,
      imageUrl: '/22214_HERO_750x500-1.jpg',
      compatibleWith: ['Autos', 'Motos', 'Generadores', 'Cortadoras', 'Botes'],
      features: [
        'Mantiene el combustible fresco hasta 24 meses',
        'Elimina la necesidad de vaciar el tanque antes del almacenamiento',
        'Previene acumulación de goma y barniz',
        'Efectivo con y sin etanol (hasta E-85)',
        'Para todos los motores de gasolina',
      ],
      description: 'El estabilizador de combustible STA-BIL Storage mantiene el combustible fresco para lograr arranques rápidos y fáciles después del almacenamiento. Elimina el agua para prevenir la corrosión y limpia carburadores e inyectores.',
      specs: [
        { label: '8oz', value: '136.44' },
        { label: '10oz', value: '177.91' },
        { label: '16oz', value: '220.67' },
        { label: '32oz', value: '254.34' },
        { label: '1gal', value: '917.27' },
      ],
      isActive: true, isFeatured: true, sortOrder: 1,
    },
    {
      ...DUMMY,
      slug: 'stabil-in-season-protection',
      name: 'STA-BIL In-Season Protection',
      model: '22275',
      labelType: 'Gasolina',
      mainUse: 'Limpia y protege el sistema de combustible en cada uso. Incrementa potencia.',
      priceBob: '335.98',
      priceUsd: null,
      imageUrl: '/22275_In-Season-32oz-HERO-thumb_750x500.jpg',
      compatibleWith: ['Autos', 'Motos', 'SUVs', 'Generadores', 'ATVs'],
      features: [
        'Limpiadores PEA de alta potencia',
        'Incrementa la potencia del motor',
        'Maximiza el rendimiento de combustible',
        'Previene daño por etanol',
        'Mantiene ralentí suave',
      ],
      description: 'STA-BIL In-Season Protection es el tratamiento de etanol #1 de EE.UU. Mantiene todos tus motores funcionando como nuevos con uso regular.',
      specs: [
        { label: '8oz Small Engine', value: '219.85' },
        { label: '10oz', value: '161.90' },
        { label: '32oz', value: '335.98' },
      ],
      isActive: true, isFeatured: true, sortOrder: 2,
    },
    {
      ...DUMMY,
      slug: 'stabil-start-your-engines',
      name: 'STA-BIL Start Your Engines!',
      model: '21214',
      labelType: 'Gasolina',
      mainUse: 'Revitaliza motores difíciles de arrancar tras almacenamiento prolongado.',
      priceBob: '150.06',
      priceUsd: null,
      imageUrl: '/21214-sta-bil-sye-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Motores 2 tiempos', 'Motores 4 tiempos', 'Motores pequeños'],
      features: [
        'Arranques rápidos y fáciles después del almacenamiento',
        'Para todos los motores pequeños de 2 y 4 tiempos',
        'Revitaliza combustible y sistema de alimentación',
        'Fácil de usar: solo agrégalo al tanque',
        'Garantía de marcha suave durante la temporada',
      ],
      description: 'STA-BIL Start Your Engines! Fuel System Revitalizer garantiza el arranque fácil de motores de 2 y 4 tiempos, suaviza el ralentí inestable y ayuda a eliminar goma y barniz del carburador.',
      specs: [{ label: '2oz Aerosol', value: '150.06' }],
      isActive: true, isFeatured: false, sortOrder: 3,
    },
    {
      ...DUMMY,
      slug: 'stabil-fast-fix',
      name: 'STA-BIL Fast Fix',
      model: '22304',
      labelType: 'Gasolina',
      mainUse: 'Solución rápida para motores pequeños que no arrancan o tienen ralentí inestable.',
      priceBob: '179.83',
      priceUsd: null,
      imageUrl: '/22304-stabil-fast-fix-8oz-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Cortadoras de césped', 'Tractores', 'Desbrozadoras', 'Quitanieves'],
      features: [
        'Devora la goma y el barniz del sistema de combustible',
        'Elimina el agua',
        'Compatible con TODOS los motores pequeños',
        'Limpia carburadores e inyectores',
        'Evita desarmado del motor',
      ],
      description: 'STA-BIL Fast Fix combate los problemas causados por combustibles con etanol. Ideal para cortadoras de césped, tractores, desbrozadoras y quitanieves.',
      specs: [
        { label: '4oz', value: '139.20' },
        { label: '8oz', value: '179.83' },
      ],
      isActive: true, isFeatured: false, sortOrder: 4,
    },
    {
      ...DUMMY,
      slug: 'stabil-fogging-oil',
      name: 'STA-BIL Fogging Oil',
      model: '22001',
      labelType: 'Gasolina',
      mainUse: 'Protege los componentes internos del motor durante el almacenamiento.',
      priceBob: '68.74',
      priceUsd: null,
      imageUrl: '/22001-sta-bil-fogging-oil-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Motores fuera de borda', 'Motores marinos', 'Motores 2T', 'Motores 4T'],
      features: [
        'Cubre componentes internos contra corrosión',
        'Desplaza la humedad del metal',
        'Lubrica cilindros y previene rayaduras',
        'Aerosol con boquilla de extensión',
        'Para todos los motores de gasolina 2 y 4T',
      ],
      description: 'STA-BIL Fogging Oil protege los componentes internos del motor durante el almacenamiento, lubricando paredes de cilindros, pistones y anillos.',
      specs: [{ label: '12oz', value: '68.74' }],
      isActive: true, isFeatured: false, sortOrder: 5,
    },
    {
      ...DUMMY,
      slug: 'stabil-carb-choke-cleaner',
      name: 'STA-BIL Carb & Choke Cleaner',
      model: '22005',
      labelType: 'Gasolina',
      mainUse: 'Limpia carburadores y disuelve depósitos de goma, barniz y carbón rápidamente.',
      priceBob: '108.60',
      priceUsd: null,
      imageUrl: '/22005-sta-bil-carb-choke-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Todos los motores carburados', 'Autos', 'Motos', 'Equipos pequeños'],
      features: [
        'Disuelve goma, barniz, suciedad y carbón',
        'Sin residuos aceitosos',
        'Seguro para convertidores catalíticos',
        'Restaura rendimiento y kilometraje',
        'Boquilla con tubo de dirección incluida',
      ],
      description: 'STA-BIL Carb & Choke Cleaner disuelve depósitos que causan arranque difícil y ralentí inestable. Restaura el rendimiento de tu motor en minutos.',
      specs: [{ label: '12oz', value: '108.60' }],
      isActive: true, isFeatured: false, sortOrder: 6,
    },
    {
      ...DUMMY,
      slug: 'stabil-2-cycle-oil',
      name: 'STA-BIL 2-Cycle Oil',
      model: '22403',
      labelType: 'Gasolina',
      mainUse: 'Aceite totalmente sintético para motores de 2 tiempos. Quema limpio, sin cenizas.',
      priceBob: '78.87',
      priceUsd: null,
      imageUrl: '/22403-sta-bil-2-cycle-oil-2oz-enhanced-750x500-min.png',
      compatibleWith: ['Motosierras', 'Cortadoras 2T', 'Motos de nieve', 'ATVs', 'Motocicletas'],
      features: [
        'Totalmente sintético, alta lubricación',
        'Sin cenizas — quema limpio, minimiza humo',
        'Estabiliza el combustible por 1 año',
        'Multi-Mezcla 50:1 y 40:1',
        'Más rentable que combustible preenvasado',
      ],
      description: 'STA-BIL 2-Cycle Oil brinda máxima protección a los componentes vitales del motor añadiendo lubricación superior. La presentación de 2.6oz rinde para 1 galón de mezcla.',
      specs: [
        { label: '2.6oz', value: '78.87' },
        { label: '13oz', value: '190.93' },
      ],
      isActive: true, isFeatured: false, sortOrder: 7,
    },
    {
      ...DUMMY,
      slug: 'stabil-small-engine-pro',
      name: 'STA-BIL Small Engine Pro',
      model: '22305',
      labelType: 'Gasolina',
      mainUse: 'Aditivo multisistema para gasolina y aceite. Limpia, lubrica y protege en un paso.',
      priceBob: '154.23',
      priceUsd: null,
      imageUrl: '/STABIL-Small-Engine-Pro-Hero-Thumb_updated_750x500-600x400.jpg',
      compatibleWith: ['Cortadoras', 'Recortadoras', 'Quitanieves', 'Hidrolavadoras', 'Generadores'],
      features: [
        'Aditivo multisistema para gasolina y aceite',
        'Restaura el rendimiento perdido',
        'Lubrica válvulas y pistones',
        'Silencia motores ruidosos',
        'Previene corrosión por etanol',
      ],
      description: 'STA-BIL Small Engine Pro limpia, lubrica y protege en un solo paso todos los motores de 2 y 4 tiempos. Compatible incluso con diésel.',
      specs: [{ label: '16oz', value: '154.23' }],
      isActive: true, isFeatured: false, sortOrder: 8,
    },
    {
      ...DUMMY,
      slug: 'stabil-starting-fluid',
      name: 'STA-BIL Starting Fluid',
      model: '22004',
      labelType: 'Gasolina',
      mainUse: 'Fluido de arranque con éter de alto contenido. Funciona hasta -65°F (-54°C).',
      priceBob: '124.06',
      priceUsd: null,
      imageUrl: '/STABIL-STARTING-FLUID-Thumb_Updated_750x500.jpg',
      compatibleWith: ['Autos', 'Camiones', 'Tractores', 'Motores marinos', 'Quitanieves'],
      features: [
        'Alto contenido de éter para arranques más rápidos',
        'Funciona hasta -65°F (-54°C)',
        'Incluye lubricante y anticorrosivo',
        'Seguro para sensores de oxígeno y catalizadores',
        'Ahorra batería y motor de arranque',
      ],
      description: 'STA-BIL Starting Fluid ayuda a que los motores de gasolina y diésel enciendan rápidamente en cualquier condición climática.',
      specs: [{ label: '11oz', value: '124.06' }],
      isActive: true, isFeatured: false, sortOrder: 9,
    },
    {
      ...DUMMY,
      slug: 'stabil-pump-protector',
      name: 'STA-BIL Pump Protector',
      model: '22007',
      labelType: 'Gasolina',
      mainUse: 'Protege hidrolavadoras durante el almacenamiento. Anticongelante para la bomba.',
      priceBob: '219.08',
      priceUsd: null,
      imageUrl: '/22007_Pump-Protector-HERO-Thumb_750x500-600x400.jpg',
      compatibleWith: ['Hidrolavadoras a gasolina', 'Hidrolavadoras eléctricas'],
      features: [
        'Protección para almacenamiento corto y largo plazo',
        'Protege sellos de pistones',
        'Propiedades anticongelantes',
        'Lubrica componentes internos',
        'Extiende la vida útil de tu hidrolavadora',
      ],
      description: 'STA-BIL Pump Protector protege las hidrolavadoras del congelamiento y la acumulación de depósitos minerales. Conecta la manguera a la entrada de agua, presiona y listo.',
      specs: [{ label: '4oz', value: '219.08' }],
      isActive: true, isFeatured: false, sortOrder: 10,
    },

    // ── DIESEL ────────────────────────────────────────────────────────────
    {
      ...DUMMY,
      slug: 'stabil-diesel-all-season',
      name: 'STA-BIL Diesel All-Season',
      model: '15226',
      labelType: 'Diesel',
      mainUse: 'Fórmula todo el año para diésel: limpia, lubrica, anti-gel y eleva cetano.',
      priceBob: '332.42',
      priceUsd: null,
      imageUrl: '/15226-stabil-all-season-diesel-20-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Todos los motores diésel', 'Camiones', 'Tractores', 'Motores marinos diésel'],
      features: [
        'Limpia y lubrica todo el sistema de combustible',
        'Desemulsiona el agua',
        'Protección anticongelante hasta -40°F (-40°C)',
        'Eleva el índice de cetano',
        'Seguro para todos los motores diésel',
      ],
      description: 'STA-BIL Diesel All-Season es la fórmula avanzada para todo el año que cubre todas tus necesidades de aditivos diésel. La botella de 20oz trata hasta 150 galones.',
      specs: [
        { label: '20oz', value: '332.42' },
        { label: '32oz', value: '343.67' },
      ],
      isActive: true, isFeatured: true, sortOrder: 11,
    },
    {
      ...DUMMY,
      slug: 'stabil-diesel-power-boost',
      name: 'STA-BIL Diesel Power Boost',
      model: '15224',
      labelType: 'Diesel',
      mainUse: '¡El máximo aumento de cetano! Eleva hasta 7 puntos y mejora la potencia.',
      priceBob: '272.23',
      priceUsd: null,
      imageUrl: '/15224-stabil-power-boost-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Autos diésel', 'Camiones ligeros', 'Tractores', 'Motores marinos diésel'],
      features: [
        'Eleva el índice de cetano hasta 7 puntos',
        'Mejora el rendimiento de combustible',
        'Mejora la potencia disponible',
        'Limpia y lubrica el sistema de combustible',
        'Seguro para todos los motores diésel',
      ],
      description: 'STA-BIL Diesel Power Boost combina acondicionador de combustible y agente de lubricidad para autos diésel, camiones, tractores y motores marinos. La botella de 20oz trata hasta 150 galones.',
      specs: [{ label: '20oz', value: '272.23' }],
      isActive: true, isFeatured: false, sortOrder: 12,
    },
    {
      ...DUMMY,
      slug: 'stabil-diesel-formula-fuel-stabilizer',
      name: 'STA-BIL Diesel Formula Fuel Stabilizer',
      model: '22254',
      labelType: 'Diesel',
      mainUse: 'Estabilizador de combustible diésel para almacenamiento y uso diario.',
      priceBob: '468.54',
      priceUsd: null,
      imageUrl: '/22254-sta-bil-diesel-32oz-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Todos los motores diésel ULSD', 'Mezclas de biodiésel'],
      features: [
        'Previene formación de lodos y sedimentos',
        'Limpia y lubrica inyectores',
        'Protege contra corrosión',
        'Elimina el agua',
        'Compatible con biodiésel',
      ],
      description: 'STA-BIL Diesel Formula mantiene el combustible fresco para arranques rápidos y fáciles. La botella de 32oz trata hasta 320 galones (1,211 litros).',
      specs: [
        { label: '32oz', value: '468.54' },
        { label: '1gal', value: '1169.25' },
      ],
      isActive: true, isFeatured: false, sortOrder: 13,
    },
    {
      ...DUMMY,
      slug: 'stabil-diesel-winter',
      name: 'STA-BIL Diesel Winter',
      model: '15225',
      labelType: 'Diesel',
      mainUse: 'Protección anticongelante (anti-gel) hasta -40°F. Para climas extremos.',
      priceBob: '244.37',
      priceUsd: null,
      imageUrl: '/15225-stabil-winter-diesel-20-enhanced-750x500-min-600x400.png',
      compatibleWith: ['Todos los motores diésel'],
      features: [
        'Previene congelamiento hasta -40°F (-40°C)',
        'Elimina el agua para prevenir corrosión',
        'Reduce punto de taponamiento del filtro hasta 36°F (20°C)',
        'Diseño patentado fácil de manejar',
        'La botella de 20oz trata hasta 150 galones',
      ],
      description: 'STA-BIL Diesel Winter protege el combustible diésel del congelamiento y reduce el punto de taponamiento del filtro en frío. Ideal para climas extremos.',
      specs: [
        { label: '20oz', value: '244.37' },
        { label: '32oz', value: '404.50' },
      ],
      isActive: true, isFeatured: false, sortOrder: 14,
    },

    // ── MARINO ────────────────────────────────────────────────────────────
    {
      ...DUMMY,
      slug: 'stabil-360-marine',
      name: 'STA-BIL 360° Marine',
      model: '22240',
      labelType: 'Marino',
      mainUse: 'El tratamiento marino #1 de EE.UU. Protección total para motores acuáticos.',
      priceBob: '481.02',
      priceUsd: null,
      imageUrl: '/22240_HERO_750x500.jpg',
      compatibleWith: ['Botes', 'Motos acuáticas', 'Motores fuera de borda', 'Motores dentro de borda'],
      features: [
        'Diseñado para climas marinos severos',
        'Protección contra daño por etanol',
        'Propiedades de eliminación de agua líderes',
        'Limpiadores PEA especializados',
        'Mantiene combustible fresco hasta 12 meses',
      ],
      description: 'STA-BIL 360° Marine: úsalo en cada carga de combustible para motores más limpios, eficientes y potentes. Compatible con todo tipo de embarcaciones. 1oz trata hasta 10 galones.',
      specs: [
        { label: '8oz', value: '163.66' },
        { label: '10oz', value: '264.52' },
        { label: '32oz', value: '481.02' },
        { label: '1gal', value: '1250.10' },
      ],
      isActive: true, isFeatured: true, sortOrder: 15,
    },
    {
      ...DUMMY,
      slug: 'stabil-marine-tune-up',
      name: 'STA-BIL Marine Tune-Up',
      model: '22313',
      labelType: 'Marino',
      mainUse: 'Solución rápida para motores marinos con funcionamiento inestable.',
      priceBob: '203.20',
      priceUsd: null,
      imageUrl: '/STABIL-Marine-Tune-Up-Hero-Thumb-600x400.png',
      compatibleWith: ['Motos acuáticas', 'Botes pequeños', 'Lanchas', 'Vehículos recreativos acuáticos'],
      features: [
        'Limpia carburadores e inyectores rápidamente',
        'Disuelve acumulación de goma y barniz',
        'Trata 20 galones (75 litros)',
        'Perfecto para botes pequeños y motos acuáticas',
        'Excelente para toda la temporada de navegación',
      ],
      description: 'STA-BIL Marine Tune-Up restaura el rendimiento perdido en cualquier embarcación a gasolina. Un solo tratamiento de 1oz trata hasta 2.5 galones.',
      specs: [{ label: '8oz', value: '203.20' }],
      isActive: true, isFeatured: false, sortOrder: 16,
    },

    // ── EXTERIOR & PROTECCIÓN ─────────────────────────────────────────────
    {
      ...DUMMY,
      slug: 'stabil-rust-stopper',
      name: 'STA-BIL Rust Stopper',
      model: '22003',
      labelType: 'Exterior',
      mainUse: 'Aerosol que previene el óxido y la corrosión en superficies metálicas.',
      priceBob: '247.03',
      priceUsd: null,
      imageUrl: '/22003-sta-bil-rust-stopper-enhanced-750x500-min.png',
      compatibleWith: ['Chasis de vehículos', 'Equipos agrícolas', 'Quitanieves', 'Tractores'],
      features: [
        'Previene óxido y corrosión en metal',
        'Fórmula resistente al agua',
        'Lubrica y protege metal agrícola',
        'Detiene el óxido ya existente',
        'Fórmula premium de mínimo escurrimiento',
      ],
      description: 'STA-BIL Rust Stopper crea una capa protectora sobre cualquier metal expuesto. También funciona como recubrimiento inferior para chasis vehicular en invierno.',
      specs: [{ label: '13oz Aerosol', value: '247.03' }],
      isActive: true, isFeatured: true, sortOrder: 17,
    },
    {
      ...DUMMY,
      slug: 'stabil-ceramic-pro-guard',
      name: 'STA-BIL Ceramic Pro-Guard',
      model: '22502',
      labelType: 'Exterior',
      mainUse: 'Protección cerámica para tolvas de cortadoras y quitanieves. Rocía y listo.',
      priceBob: '233.78',
      priceUsd: null,
      imageUrl: '/22502csr-sta-bil-ceramic-pro-guard-enhanced-min-600x400.png',
      compatibleWith: ['Cortadoras de césped', 'Quitanieves', 'Equipos eléctricos', 'Equipos a gasolina'],
      features: [
        'Protección cerámica fácil de aplicar',
        'Previene acumulación de césped y nieve',
        'Seguro en metal y plástico',
        'Protección avanzada contra óxido',
        'También funciona como spray de detallado',
      ],
      description: 'STA-BIL Ceramic Pro-Guard — simplemente rocía y deja curar 24 horas. Las acumulaciones futuras se limpian fácilmente con una manguera.',
      specs: [{ label: '10oz', value: '233.78' }],
      isActive: true, isFeatured: false, sortOrder: 18,
    },
    {
      ...DUMMY,
      slug: 'stabil-blade-guard',
      name: 'STA-BIL Blade Guard',
      model: '22503',
      labelType: 'Exterior',
      mainUse: 'Lubricante para cuchillas de corte. Fórmula bio, seguro para plantas.',
      priceBob: '198.89',
      priceUsd: null,
      imageUrl: '/22503-sta-bil-blade-guard-min-600x400.png',
      compatibleWith: ['Cortasetos', 'Podadoras', 'Desbrozadoras', 'Tijeras de podar', 'Hachas'],
      features: [
        'Mantiene el filo de la cuchilla',
        'Limpia y lubrica en un paso',
        'Fórmula bio-based, amigable con plantas',
        'Previene el óxido',
        'Equipos eléctricos y a gasolina',
      ],
      description: 'STA-BIL Blade Guard lubrica y protege herramientas de corte con una fórmula de base biológica completamente segura para tu jardín.',
      specs: [{ label: '12oz', value: '198.89' }],
      isActive: true, isFeatured: false, sortOrder: 19,
    },
    {
      ...DUMMY,
      slug: 'stabil-sport-bike-cleaner',
      name: 'STA-BIL Sport Bike Cleaner & Protectant',
      model: '22504',
      labelType: 'Exterior',
      mainUse: 'Limpia, da brillo y protege tu bicicleta contra óxido, UV y corrosión.',
      priceBob: '354.17',
      priceUsd: null,
      imageUrl: '/22504csr-sta-bil-bike-cleaner-and-protectant-enhanced-v2-min-600x400.png',
      compatibleWith: ['Bicicletas', 'Metal', 'Fibra de carbono', 'Caucho', 'Plástico', 'Cuero'],
      features: [
        'Limpia y da brillo en un solo paso',
        'Protege contra agua, óxido, UV y corrosión',
        'Revive acabados opacos',
        'Funciona en metal, carbono, caucho, plástico',
        'Secado rápido con escudo protector',
      ],
      description: 'STA-BIL Sport Bike Cleaner & Protectant mantiene tu bicicleta como nueva. Rocía sobre paño suave y limpia todas las superficies. Reaplicar cada 5 semanas.',
      specs: [{ label: '10oz', value: '354.17' }],
      isActive: true, isFeatured: false, sortOrder: 20,
    },
    {
      ...DUMMY,
      slug: 'stabil-gun-clp',
      name: 'STA-BIL Gun CLP',
      model: '22405',
      labelType: 'Exterior',
      mainUse: 'Limpia, Lubrica y Protege armas de fuego. Fórmula biodegradable.',
      priceBob: '243.86',
      priceUsd: null,
      imageUrl: '/22405-sta-bil-gun-clp-enhanced-min-600x400.png',
      compatibleWith: ['Pistolas', 'Rifles', 'Escopetas'],
      features: [
        'Elimina residuos de pólvora y plomo',
        'Restaura la precisión',
        'Aditivo antidesgaste de larga duración',
        'Barrera protectora duradera',
        'Biodegradable y protege contra corrosión',
      ],
      description: 'STA-BIL Gun CLP está diseñado para limpiar, lubricar y proteger tus armas de fuego. Funciona con pistolas, rifles y escopetas.',
      specs: [{ label: '8oz', value: '243.86' }],
      isActive: true, isFeatured: false, sortOrder: 21,
    },
    {
      ...DUMMY,
      slug: 'stabil-bike-chain-cleaner',
      name: 'STA-BIL Bike Chain Cleaner & Lubricant',
      model: '22406',
      labelType: 'Exterior',
      mainUse: 'Limpia y lubrica cadenas de bicicleta en un solo paso. Biodegradable.',
      priceBob: '251.87',
      priceUsd: null,
      imageUrl: '/22406-sta-bil-bike-chain-cleaner-lubricant-enhanced-min-600x400.png',
      compatibleWith: ['Cadenas de bicicleta', 'Cables', 'Desviadores'],
      features: [
        'Limpia y lubrica en un solo paso',
        'Penetra profundamente en cadena y cables',
        'Previene el óxido',
        'Lubricante premium biodegradable',
        'Hecho en EE.UU.',
      ],
      description: 'STA-BIL Bike Chain Cleaner and Lubricant afloja suciedad y reduce fricción para mejorar el rendimiento de transmisión. Aplica mientras giras el pedal hacia atrás.',
      specs: [{ label: '8oz', value: '251.87' }],
      isActive: true, isFeatured: false, sortOrder: 22,
    },
  ]);

  console.log('✅ Seed completado — 22 productos STA-BIL insertados');
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Error en seed:', err);
  process.exit(1);
});
